language: python

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4052245BD4284CDD
  - echo "deb https://repo.iovisor.org/apt/$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/iovisor.list
  - sudo apt update
  - sudo apt install python3-bcc

install: pip install -r requirements-test.txt

script:
  - pytest tests/unit/
