language: python

before_install:
  - sudo apt-get -y install python3-bcc
  - export PYTHONPATH="$PYTHONPATH:/usr/lib/python3/dist-packages"

install:
  - pip install -r test-requirements.txt

script:
  - pytest -p tests/unit/
